DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE pfile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  p_id INTEGER NOT NULL,
  fullname TEXT NOT NULL,
  adress TEXT NOT NULL,
  zipcode TEXT NOT NULL,
  FOREIGN KEY (p_id) REFERENCES user (id)
);

CREATE TABLE datatrain (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  d_id INTEGER NOT NULL,
  moisture INTEGER NOT NULL,
  weather TEXT NOT NULL,
  temperature TEXT NOT NULL,
  humidity TEXT NOT NULL,
  FOREIGN KEY (d_id) REFERENCES user (p_id)
);