DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE pfile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  p_id INTEGER NOT NULL,
  fullname TEXT NOT NULL,
  adress TEXT NOT NULL,
  zipcode TEXT NOT NULL,
  FOREIGN KEY (p_id) REFERENCES user (id)
);